@app_HostAddress = http://localhost:8080/api/products

POST http://localhost:8080/register
Content-Type: application/json
Accept: application/json

{

  "fullName": "fabio",
  "cpf": "35333517879",
  "login": "binho77",
    "email": "binho3@gmail.com",
  "password": "123"
}
###
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "login": "binho77",
  "password": "$2a$10$5p0vAE2mz2Riog4GZs8AZeJ.IaEMkFteTQDkr95a7TDDuAi8.aEj6"
}